### ISSUE TITLE
Issue when Darg and drop multiple files. Multiple files will not show.

### ISSUE THREAD

**Issue by chikhalenakush** [jeromebq/AttachmentEmail#1]
I have used your solution in one of my trial instance. When I drag and drop single file. It does appear correct. But when I do that for multiple file, it will show only 1 file. I had to refresh the entire page to see the attachments in Custom control.

------------
Solution
--------
I compiled the project and found that under drophandler.ts file 
for the below line of code

```this.attachmentSource.next(new Attachment(new EntityReference('activitymimeattachment', response.id.guid ), this.TrimFileExtension(file.name), this.GetFileExtension(file.name), false));```

You are using response.id.guid which will not return guid rather you should use response.id or response.id.toString()
so updated/changed line of code will be

 ``` this.attachmentSource.next(new Attachment(new EntityReference('activitymimeattachment', response.id.toString()), this.TrimFileExtension(file.name), this.GetFileExtension(file.name), false));```

**Comment by jeromebq** [comment]
Hello,

Thanks for your help. I fixed the issue.

Jerome
